### ISSUE TITLE
Stuck on gnome 44.9

### ISSUE THREAD

**Issue by trwy7** [Nova1545/gnome-shell-extension-customreboot#12]
I cannot get past "Fix grub.conf perms", even though I have the extension set to efibootmgr, not grub. 
![image](https://github.com/Nova1545/gnome-shell-extension-customreboot/assets/47907719/e69bcb28-94bd-4fbc-ad3f-b1317d828c82)
Gnome 44.9 on debian 12

**Comment by Nova1545** [comment]
Try disabling and re-enabling the extension

**Comment by trwy7** [comment]
Nope, still fails.

**Comment by Nova1545** [comment]
So i'm gonna hazard a guess there is something broken within the gnome 44 release of the extension that I fixed and never back ported because 45 was released. If I have time tonight I'll take a look and see what I changed
