### ISSUE TITLE
ACTUALLY reboot into another OS

### ISSUE THREAD

**Issue by devlocalhost** [Nova1545/gnome-shell-extension-customreboot#3]
because whats the point of rebooting manually if the description is "Reboot into another OS directly from GNOME."? or maybe add an option to reboot after selecting the OS?

**Comment by Nova1545** [comment]
The extension does indeed reboot into another OS, use this plugin daily for exactly that purpose. You should select the OS from the list and it should them ask for root (to run grub or whatever else), then prompt you to restart (Showing a restart dialog). 
Are you using grub for boot or something else (Such as systemd-boot)? What version of gnome? (Tested is 43)

**Comment by devlocalhost** [comment]
> The extension does indeed reboot into another OS, use this plugin daily for exactly that purpose. You should select the OS from the list and it should them ask for root (to run grub or whatever else), then prompt you to restart (Showing a restart dialog). Are you using grub for boot or something else (Such as systemd-boot)? What version of gnome? (Tested is 43)

After selecting the os, I do not see any reboot dialog. I see only one dialog, the grub-reboot one

Also, I remembered that I cannot reboot from gnome too, because I'm using Wayland, so maybe, it's that (I can reboot and logout fine in xorg, but not in Wayland. Nothing happens when I click reboot or logout from gnome quick system buttons)
