### ISSUE TITLE
Remove Grub Timeout

### ISSUE THREAD

**Issue by MehulKhanna** [Nova1545/gnome-shell-extension-customreboot#5]
Can you make the extension remove the Grub Timeout while rebooting into another OS? So we don't have to wait a few seconds before booting into the OS that we already selected through the extension. It would have to be removed only for the next boot just like how the default OS is selected by the extension.

**Comment by Nova1545** [comment]
So I didn't think this was possible at all, seems I was wrong. The next release of the extension will be able to skip the grub timeout meaning quick reboots (Hurray!). I will close this issue once I release the next version

**Comment by Nova1545** [comment]
Relevant commit if you wanna check it out before the proper release 5cb34f3
