### ISSUE TITLE
Incompatible with Gnome 45

### ISSUE THREAD

**Issue by yasscaleb** [Nova1545/gnome-shell-extension-customreboot#8]
there are breaking changes with gnome 45

**Comment by Nova1545** [comment]
I currently don't have a working Gnome 45 install yet. As soon as I find some free time I will work on updating the extension to support Gnome 45

Thanks for the headsup above the breaking changes

**Comment by sneuweger** [comment]
looking forward to get this great extension on Gnome 45!

**Comment by peter-lyons-kehl** [comment]
Suggest borrowing/looking at https://extensions.gnome.org/extension/5105/reboottouefi = https://github.com/UbayGD/reboottouefi. It works in GNOME 45, and also in Manjaro Linux.

(It doesn't list any license, so presumably Public Domain. Or ask the author.)

**Comment by Nova1545** [comment]
An update is coming but im struggling to get it working again (Thanks Gnome). I will push a commit tomorrow

**Comment by Nova1545** [comment]
So for the very long wait. The updated version should be up shortly (Just waiting on review) and **_should_** function without any issues
