### ISSUE TITLE
systemdBoot.js tries to switch boot entry with GRUB

### ISSUE THREAD

**Issue by filipkemuel** [Nova1545/gnome-shell-extension-customreboot#9]
There are several errors in systemdBoot.js

Firstly Title and ID has been switched around in `bootOptions.set`
So titles becomes IDs and IDs become titles.

But then once that is fixed the code to find the default boot option fails because that also has switched them around.

Secondly `SetBootOption` runs `/usr/sbin/grub-reboot`

So it definitely doesn't work.

I'm going to make a pull request that fixes this and makes systemd-boot finally work.

**Comment by Nova1545** [comment]
I will review your pull request and merge this tomorrow
